### ISSUE TITLE
did this work in cura 4.0.0 ?

### ISSUE THREAD

**Issue by marcottt** [AmedeeBulle/ShowLayer#1]
searching a way to have layer number on display, i think this ok but unable to install on cura 4.0.0

**Comment by AmedeeBulle** [comment]
I have no idea -- I stopped upgrading Cura as it was impossible for me to have reproducible prints across all changes...

I'll install it and try.

**Comment by AmedeeBulle** [comment]
Cura 4.0 has a new plugin API, and plugins apparently need to be registered on the marketplace.

In short, this won't work anymore in Cura 4.0
